apiVersion: v1
kind: Service
metadata:
  name: user-microservice
  namespace: dwetter-develop
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: user-microservice
  type: ClusterIP
